import "~/styles/globals.css";

import { Inter, Poppins } from "next/font/google";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-sans",
});

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-poppins",
});

export const metadata = {
	title: "Dynamic Dashboard",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/dynamicIcon.svg" }],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`font-sans ${inter.variable} ${poppins.variable}`}
			>
				{children}
			</body>
		</html>
	);
}
